### ISSUE TITLE
Proposal - add more complex FROM clause parsing

### ISSUE THREAD

**Issue by m1n0** [containerbuildsystem/dockerfile-parse#105]
I wrote a more complex FROM clause parsing, and it currently sits in a opensourced piece of software - would you be interested in transferring it to your library? It would make much more sense to have it in here. Its used in production, covered with tests, and should be pretty much a direct copy-paste. Its the `DockerImageId` class here https://github.com/kiwicom/the-zoo/blob/master/zoo/analytics/tasks/utils.py

Tests are here https://github.com/kiwicom/the-zoo/blob/master/test/analytics/tasks/test_utils.py

Let me know, I will submit PR if you are interested.

**Comment by MartinBasti** [comment]
Hello,
Thank you for your interest into contribution! :rocket: 

Your format (and class properties) seems very specific to your use cases:
`my.registry.com:5005/special-name/my-image/namespace/another-namespace:0.1.1-alpine3.9 as base-image`

We are using have images with different tag formats and different namespace structure. (For example quay.io registry doesn't support such nested namespace structure)

Here we need more generic handling of image name. I'd keep dockerfile-parse simple and let users choose how to parse it with their favorite library.

For example we use this: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/util.py#L91

It's simple enough for our use cases.

**Comment by m1n0** [comment]
I see, could you maybe outline what the different tag formats and namespaces structures are? I was aiming to do it as general as possible, did quite a lot of research on different formats used around etc. 
I know some registries do not support nested namespaces for example, but my parser handles that ok, as far as I know different formats are only a subset of what my parser supports, not something completely different that would break it.
In case there are such different formats used that I cannot make compatible with what I support already then I understand.

**Comment by athos-ribeiro** [comment]
I believe what Martin meant with his comment was that maybe restricting or labelling the data in the from instruction to do more than specified by the container build engines (e.g., https://docs.docker.com/engine/reference/builder/#from) may be the role of some other tool instead of a general purpose parser (unless we could make the parser more generic).

One use case the parser does not cover, which is definitely desired, is handling digest references. 

For instance  `ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2` is parsed as having the reponame as `ubuntu@sha256` and the tag and version as the digest.

Also, if we use just the digest, the hash function is parsed as being the repository name.

Moreover, how should the parser behave if it had to parse an ipv6 literal? See https://github.com/docker/distribution/pull/2899 

Now for specifics, let's look at the Fedora case, where '-' may be used on the tag to separate the version from the release for a component NVR (Name, Version, Release). Also note this is not so different for other distros, such as Debian (however, AFAIK, they do not ship containers as part of the distro). Now, let's say wehave an image named `registry.fedoraproject.io/my-image:1.0.0-123.4`.

What makes sense to parse as OS in your parser, should actually be the release. Furthermore, if we ad a tilde there to point to a pre-release `1.0.0-1~beta`, we would get that split in the OS components.

Hence, I do not think a copy-paste of the parser pointed here would be generic enough for dockerfile-parse. However, a more complex (less restrictive, in the sense it would not raise errors, but maybe warnings) generic parser would be nice to have as long as it would not break backward compatibility with former versions of dockerfile-parse. For instance, we could start with the abstractions shown in https://docs.docker.com/engine/reference/builder/#from

**Comment by lcarva** [comment]
Thank you for the suggestion, but based on the previous comment this is not something we want to support.
